# Generated by Django 5.2.6 on 2026-01-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_subscriptiondetails_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='purchase_status',
            field=models.CharField(choices=[('purchased', 'Purchased'), ('restored', 'Restored'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20),
        ),
    ]
