# Generated by Django 5.2.6 on 2026-01-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_subscriptiondetails_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='purchase_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('failed', 'Failed')], max_length=20),
        ),
    ]
