# Generated by Django 5.2.6 on 2026-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
