# Generated by Django 5.2.6 on 2026-05-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_phone_otp_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_otp_attempts',
        ),
    ]
